[package]
name = "nslookup"
version.workspace = true
edition.workspace = true

[[bin]]
name = "nslookup"
path = "src/main.rs"

[dependencies]
nrlib = { workspace = true, optional = true, features = ["std"] }
nexa_boot_info.workspace = true

[features]
default = []
use-nrlib = ["nrlib", "nrlib/panic-handler"]
use-nrlib-std = ["nrlib"]
