[package]
name = "edit"
version.workspace = true
edition.workspace = true
description = "A Vim-like text editor with Vim Script support for NexaOS"

[[bin]]
name = "edit"
path = "src/main.rs"

[dependencies]
nrlib = { workspace = true, optional = true, features = ["panic-handler"] }
nexa_boot_info.workspace = true

[features]
default = ["use-nrlib"]
use-nrlib = ["nrlib"]
use-nrlib-std = ["nrlib", "nrlib/std"]
