[package]
name = "nrlib"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["rlib", "staticlib"]

[profile.release]
panic = "abort"

[features]
default = ["panic-handler"]
panic-handler = []
std = []

[dependencies]
nexa_boot_info = { path = "../../boot/boot-info" }
