[package]
name = "nurl"
version.workspace = true
edition.workspace = true

[[bin]]
name = "nurl"
path = "src/main.rs"

[dependencies]
nrlib = { workspace = true, optional = true, features = ["panic-handler"] }
nexa_boot_info.workspace = true
nssl = { path = "../../nssl", optional = true }

[features]
default = ["use-nrlib", "https"]
use-nrlib = ["nrlib"]
use-nrlib-std = ["nrlib", "nrlib/std"]
https = ["nssl"]
# Future HTTP/2 and HTTP/3 support
http2 = []
http3 = []
