[package]
name = "libc"
version = "0.2.177"
edition = "2021"

[lib]
name = "c"
crate-type = ["rlib", "staticlib"]

[features]
default = ["std"]
std = []
rustc-dep-of-std = []
align = []
extra_traits = []
